
version: 2

models:
  - name: species
    description: "All species"
    columns:
      - name: id
        description: "Species id"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "Plant species name"
        data_tests:
          - not_null
      - name: is_active
        description: "Activation flag"
        data_tests:
          - not_null

  - name: species_active
    description: "Active species only"
    columns:
      - name: id
        description: "PK"
        data_tests:
          - unique
          - not_null

  - name: species_origin
    description: "Contry codes for species"
    columns:
      - name: id
        description: "Species id"
        data_tests:
          - unique
          - not_null
      - name: alpha_2
        description: "Country code Alpha 2"
        data_tests:
          - unique
          - not_null
          