
version: 2

models:
  - name: countries
    description: "Countries and codes"
    columns:
      - name: country
        description: "Country name"
        data_tests:
          - unique
          - not_null
      - name: alpha_2
        description: "Country code Alpha 2"
        data_tests:
          - unique
          - not_null
      - name: alpha_3
        description: "Country code Aplha 3"
        data_tests:
          - unique
          - not_null
